/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ctrlInicio;
import controlador.ctrlAuditoria;
import modelo.Arbitros;
import modelo.Auditoria;

/**
 *
 * @author marvi
 */
public class frmAuditoria extends javax.swing.JPanel {

    /**
     * Creates new form frmPerfil2
     */
    public frmAuditoria() {
        initComponents();
        
        Auditoria modeloAuditoria = new Auditoria();
        frmAuditoria panelPerfil = this;
        frmHome vista = new frmHome();
        
        
        ctrlAuditoria controlador = new ctrlAuditoria(modeloAuditoria, vista, panelPerfil);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbAuditoria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnGenerarReporte = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNoticias = new javax.swing.JButton();
        txtIdTorneo = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbAuditoria.setBackground(new java.awt.Color(51, 51, 51));
        jtbAuditoria.setForeground(new java.awt.Color(255, 255, 255));
        jtbAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbAuditoria);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 590, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Generar reporte");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        btnGenerarReporte.setBackground(new java.awt.Color(255, 0, 51));
        btnGenerarReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarReporte.setText("Generar");
        jPanel1.add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, 60));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Auditoría");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 15, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(794, 481));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        btnNoticias.setBackground(new java.awt.Color(255, 0, 51));
        btnNoticias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNoticias.setForeground(new java.awt.Color(255, 255, 255));
        btnNoticias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/news.png"))); // NOI18N
        btnNoticias.setText("Noticias");
        jPanel1.add(btnNoticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 140));
        jPanel1.add(txtIdTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 456, 20, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnGenerarReporte;
    public static javax.swing.JButton btnNoticias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jtbAuditoria;
    public static javax.swing.JLabel txtIdTorneo;
    // End of variables declaration//GEN-END:variables
}
