/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.ImageIcon;

/**
 *
 * @author marvi
 */
public class frmBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    public frmBienvenida() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/img/logodillo.png")).getImage());
        setResizable(false);
        
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlTitulo = new javax.swing.JLabel();
        JlTitulo3 = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        JlTitulo1 = new javax.swing.JLabel();
        JlTitulo2 = new javax.swing.JLabel();
        JlTitulo4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnComenzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        JlTitulo.setBackground(new java.awt.Color(0, 0, 0));
        JlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JlTitulo.setForeground(new java.awt.Color(255, 0, 51));
        JlTitulo.setText("Inicio");
        JlTitulo.setPreferredSize(new java.awt.Dimension(107, 50));

        JlTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        JlTitulo3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JlTitulo3.setForeground(new java.awt.Color(255, 0, 51));
        JlTitulo3.setText("Bienvenido a");
        JlTitulo3.setPreferredSize(new java.awt.Dimension(107, 50));

        btnIniciarSesion.setBackground(new java.awt.Color(255, 51, 51));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlTitulo1.setBackground(new java.awt.Color(0, 0, 0));
        JlTitulo1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JlTitulo1.setForeground(new java.awt.Color(255, 0, 51));
        JlTitulo1.setText("Sports");
        JlTitulo1.setPreferredSize(new java.awt.Dimension(107, 50));
        jPanel1.add(JlTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 64, 130, 40));

        JlTitulo2.setBackground(new java.awt.Color(0, 0, 0));
        JlTitulo2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JlTitulo2.setForeground(new java.awt.Color(255, 0, 51));
        JlTitulo2.setText("Bienvenido a");
        JlTitulo2.setPreferredSize(new java.awt.Dimension(107, 50));
        jPanel1.add(JlTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 64, 248, 40));

        JlTitulo4.setBackground(new java.awt.Color(0, 0, 0));
        JlTitulo4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JlTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        JlTitulo4.setText("Dillo");
        JlTitulo4.setPreferredSize(new java.awt.Dimension(107, 50));
        jPanel1.add(JlTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 64, 96, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dilogo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 122, 202, -1));

        btnComenzar.setBackground(new java.awt.Color(255, 51, 51));
        btnComenzar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btnComenzar.setForeground(new java.awt.Color(255, 255, 255));
        btnComenzar.setText("Comenzar");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 359, 221, 62));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        
        frmLogin.initFrmLogin();
        this.dispose();
    }//GEN-LAST:event_btnComenzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlTitulo;
    private javax.swing.JLabel JlTitulo1;
    private javax.swing.JLabel JlTitulo2;
    private javax.swing.JLabel JlTitulo3;
    private javax.swing.JLabel JlTitulo4;
    public javax.swing.JButton btnComenzar;
    public javax.swing.JButton btnIniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
