/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ctrlInicio;
import controlador.ctrlReportesMenu;

/**
 *
 * @author marvi
 */
public class frmReportes extends javax.swing.JPanel {

    /**
     * Creates new form frmPartidos2
     */
    public frmReportes() {
        initComponents();
        
        frmReportes panelPartidos = this;
        frmHome vista = new frmHome();
        
        
        ctrlReportesMenu controlador = new ctrlReportesMenu(vista, panelPartidos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPartidos = new javax.swing.JButton();
        btnNoticias = new javax.swing.JButton();
        btnEquipos = new javax.swing.JButton();
        btnJugadores = new javax.swing.JButton();
        btnArbitros = new javax.swing.JButton();
        btnTorneos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIdTorneo = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(791, 481));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(794, 481));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Selecciona un reporte para generar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnPartidos.setBackground(new java.awt.Color(255, 0, 51));
        btnPartidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPartidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPartidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/partidos.png"))); // NOI18N
        btnPartidos.setText("Partidos");
        jPanel1.add(btnPartidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 230, 140));

        btnNoticias.setBackground(new java.awt.Color(255, 0, 51));
        btnNoticias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNoticias.setForeground(new java.awt.Color(255, 255, 255));
        btnNoticias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/news.png"))); // NOI18N
        btnNoticias.setText("Noticias");
        jPanel1.add(btnNoticias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 140));

        btnEquipos.setBackground(new java.awt.Color(255, 0, 51));
        btnEquipos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEquipos.setForeground(new java.awt.Color(255, 255, 255));
        btnEquipos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/equipos.png"))); // NOI18N
        btnEquipos.setText("Equipos");
        jPanel1.add(btnEquipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 230, 140));

        btnJugadores.setBackground(new java.awt.Color(255, 0, 51));
        btnJugadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnJugadores.setForeground(new java.awt.Color(255, 255, 255));
        btnJugadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugadores.png"))); // NOI18N
        btnJugadores.setText("Jugadores");
        jPanel1.add(btnJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 280, -1, 140));

        btnArbitros.setBackground(new java.awt.Color(255, 0, 51));
        btnArbitros.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnArbitros.setForeground(new java.awt.Color(255, 255, 255));
        btnArbitros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arbitro.png"))); // NOI18N
        btnArbitros.setText("Arbitros");
        jPanel1.add(btnArbitros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 230, 140));

        btnTorneos.setBackground(new java.awt.Color(255, 0, 51));
        btnTorneos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTorneos.setForeground(new java.awt.Color(255, 255, 255));
        btnTorneos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/torneos.png"))); // NOI18N
        btnTorneos.setText("Torneos");
        jPanel1.add(btnTorneos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(794, 481));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));
        jPanel1.add(txtIdTorneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 10, 20, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnArbitros;
    public static javax.swing.JButton btnEquipos;
    public static javax.swing.JButton btnJugadores;
    public static javax.swing.JButton btnNoticias;
    public static javax.swing.JButton btnPartidos;
    public static javax.swing.JButton btnTorneos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtIdTorneo;
    // End of variables declaration//GEN-END:variables
}
